In [60]:
# %load influxdb.py
import influxdb_client, os, time
from influxdb import InfluxDBClient, Point, WritePrecision, DataFrameClient
from influxdb_client.client.write_api import SYNCHRONOUS
from tqdm import tqdm
def connection():
    #token = os.environ.get("INFLUXDB_TOKEN")
    token = 'Cip4RtUo-rRcBvCAFCObxJZs_pxZGdGhXtR6YBD97gNKvyLyWZvbElm-RbwL-RU847N0A94UqQtjKML7s36tvw=='
    org = "bosch"
    #url = "https://us-west-2-1.aws.cloud2.influxdata.com/"

    client = DataFrameClient(url="http://localhost:8086",token=token, org=org)
    print('connection done')
    return client

ImportError: cannot import name 'DataFrameClient' from 'influxdb' (c:\disk\AI\database_do\influxdb.py)

In [56]:
pd.set_option('display.max_columns', 600)
pd.set_option('display.max_rows', 500)

In [57]:
# %load influxdb_write.py
client = connection()
bucket="mybucket"

write_api = client.write_api(write_options=SYNCHRONOUS)
   
for value in range(5):
  point = (
    Point("measurement1")
    .tag("tagname1", "tagvalue1")
    .field("field1", value)
  )
  write_api.write(bucket=bucket, org="bosch", record=point)
  time.sleep(1) # separate points by 1 second

print(f'write is done')

connection done
write is done

In [58]:
client.get_list_database()

AttributeError: 'InfluxDBClient' object has no attribute 'get_list_database'

In [39]:
# %load influxdb_read.py
import pandas as pd
client = connection()
query_api = client.query_api()
csv_result = query_api.query_csv('from(bucket:"mybucket") |> range(start: -10m)')

df = pd.DataFrame(data=csv_result)
df.columns = df.iloc[0]
df = df.iloc[1:,:]

#print(df)

connection done

In [41]:
client.get_databases

AttributeError: 'InfluxDBClient' object has no attribute 'get_databases'

In [44]:
df[:10]

,#datatype,string,long,dateTime:RFC3339,dateTime:RFC3339,dateTime:RFC3339,double,string,string,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,#group,false,false,true,true,false,false,true,true,None,None,None,None,None,None,None,None,None,None,None,None,None
2,#default,_result,,,,,,,,None,None,None,None,None,None,None,None,None,None,None,None,None
3,,result,table,_start,_stop,_time,_value,_field,_measurement,None,None,None,None,None,None,None,None,None,None,None,None,None
4,,,0,2022-11-21T04:57:12.6803641Z,2022-11-21T05:07:12.6803641Z,2022-11-21T04:57:18.4660839Z,5259,counter,boltdb_reads_total,None,None,None,None,None,None,None,None,None,None,None,None,None
5,,,0,2022-11-21T04:57:12.6803641Z,2022-11-21T05:07:12.6803641Z,2022-11-21T04:57:28.4792006Z,5261,counter,boltdb_reads_total,None,None,None,None,None,None,None,None,None,None,None,None,None
6,,,0,2022-11-21T04:57:12.6803641Z,2022-11-21T05:07:12.6803641Z,2022-11-21T04:57:38.4658074Z,5271,counter,boltdb_reads_total,None,None,None,None,None,None,None,None,None,None,None,None,None
7,,,0,2022-11-21T04:57:12.6803641Z,2022-11-21T05:07:12.6803641Z,2022-11-21T04:57:48.4687073Z,5273,counter,boltdb_reads_total,None,None,None,None,None,None,None,None,None,None,None,None,None
8,,,0,2022-11-21T04:57:12.6803641Z,2022-11-21T05:07:12.6803641Z,2022-11-21T04:57:58.4731106Z,5275,counter,boltdb_reads_total,None,None,None,None,None,None,None,None,None,None,None,None,None
9,,,0,2022-11-21T04:57:12.6803641Z,2022-11-21T05:07:12.6803641Z,2022-11-21T04:58:08.4770659Z,5277,counter,boltdb_reads_total,None,None,None,None,None,None,None,None,None,None,None,None,None
10,,,0,2022-11-21T04:57:12.6803641Z,2022-11-21T05:07:12.6803641Z,2022-11-21T04:58:18.4761537Z,5279,counter,boltdb_reads_total,None,None,None,None,None,None,None,None,None,None,None,None,None